update

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,7 +1,24 @@
-#!/usr/bin/env bash
-# Secure copy from the client to a server
-if [ "$#" -lt 4 ]; then
-    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY";
+#!/bin/bash/env bash
+
+# Check if less than 4 parameters are passed
+if [ $# -lt 4 ]; then
+    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+    exit 1
+fi
+
+# Assign parameters to variables
+FILE_PATH=$1
+SERVER_IP=$2
+USERNAME=$3
+SSH_KEY=$4
+
+# Transfer the file to the server using scp
+scp -i "$SSH_KEY" -o StrictHostKeyChecking=no "$FILE_PATH" "$USERNAME@$SERVER_IP":~/ 
+
+# Check if scp command executed successfully
+if [ $? -eq 0 ]; then
+    echo "File transferred successfully"
 else
-    scp -i "$4" -o "StrictHostKeyChecking=no" "$1" "$3@$2":~/;
+    echo "Error transferring file"
+    exit 1
 fi
