update

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -4,10 +4,16 @@
 if [ $# -lt 4 ]; then
   echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
 else
-  file_path=$1
-  server_ip=$2
-  username=$3
-  ssh_key=$4
+FILE_PATH="$1"
+SERVER_IP="$2"
+USERNAME="$3"
+SSH_KEY="$4"
   
-  scp -o StrictHostKeyChecking=no -i "$ssh_key" "$file_path" "$username@$server_ip:~"
+ scp -o StrictHostKeyChecking=no -i "$SSH_KEY" "$FILE_PATH" "$USERNAME@$SERVER_IP":~/ 
+
+if [ "$?" -eq 0 ]; then
+    echo "File transferred successfully."
+else
+    echo "Error: File transfer failed."
 fi
+
