update

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,26 +1,26 @@
-#!/bin/bash/env bash
-
-# Transfers a file from our client to a server
-
-if [ $# -lt 4 ]; then
-    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
-    exit 1
+#!/usr/bin/env bash
+# Checking for command-line argument
+if [ $# -lt 4 ]
+then
+  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+  exit 1
 fi
 
-# Assign parameters to variables
-FILE_PATH=$1
-SERVER_IP=$2
-USERNAME=$3
-SSH_KEY=$4
+# Assigning Arguments to variables
 
-# Transfer the file to the server using scp
-scp -i "$SSH_KEY" -o StrictHostKeyChecking=no "$FILE_PATH" "$USERNAME@$SERVER_IP":~/ 
+path_to_file=$1
+ip=$2
+username=$3
+path_to_ssh_key=$4
 
-# Check if scp command executed successfully
-if [ $? -eq 0 ]; then
-    echo "File transferred successfully"
+
+# Disabbling Strict Host Key checking
+scp -o "StrictHostKeyChecking no" -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/"
+
+# Checking if the transfer was successful
+if [ $? -eq 0 ]
+then
+  echo "FILE TRANSFER WAS SUCCESSFULL"
 else
-    echo "Error transferring file"
-    exit 1
+  echo "FILE TRANSFER FAILED"
 fi
-
